name: EC2 File Transfer via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  transfer-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          cat << 'KEYEOF' > ~/.ssh/id_rsa
          ${{ secrets.SSH_PRIVATE_KEY }}
          KEYEOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_A_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_B_HOST }} >> ~/.ssh/known_hosts

      - name: Download file from EC2-A
        run: |
          sftp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_A_HOST }} <<EOF
          get /home/ubuntu/testfile.txt /tmp/testfile.txt
          EOF

      - name: Upload file to EC2-B
        run: |
          sftp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_B_HOST }} <<EOF
          put /tmp/testfile.txt /home/ubuntu/testfile.txt
          EOF
